### ISSUE TITLE
ant deployTwilio failure [Twilio_TestConference.testTwilioParticipants_get -- TwilioRestException: Script-thrown exception]

### ISSUE THREAD

**Issue by Samrudhi** [twilio/twilio-salesforce#43]
$ ant deployTwilio
Buildfile: /Users/samrudhipatil/codebase/twilio-salesforce-master/install/build.xml

deployTwilio:
     [echo] Deploying Twilio Helper Library for Salesforce...
[sf:deploy] Request for a deploy submitted successfully.
[sf:deploy] Request ID for the current deploy task: 0Af60000000F5iaCAC
[sf:deploy] Waiting for server to finish processing the request...
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: InProgress (0/76)  -- Processing Type: CustomObject
[sf:deploy] Request Status: InProgress (4/76)  -- Processing Type: ApexClass
[sf:deploy] Request Status: InProgress (4/76)  -- Processing Type: ApexClass
[sf:deploy] Request Status: InProgress (4/76)  -- Processing Type: ApexClass
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: InProgress
[sf:deploy] Request Status: InProgress (0/268)  -- Running Test: addAttachedByContactIdTest.myUnitTest
[sf:deploy] Request Status: InProgress (3/268)  -- Running Test: addCases_Test.theTests
[sf:deploy] Request Status: InProgress (7/268)  -- Running Test: addPartnerUsersToGroupTest.TestUpdatePartnerUsersToGroup
[sf:deploy] Request Status: InProgress (9/268)  -- Running Test: ApprovalQuoteLineController.test
[sf:deploy] Request Status: InProgress (10/268)  -- Running Test: AssetReturnRequestTest.myUnitTest
[sf:deploy] Request Status: InProgress (21/268)  -- Running Test: CallCenterCaseNotification.testAddRegionContact
[sf:deploy] Request Status: InProgress (26/268)  -- Running Test: CampaigmMemberTriggerHandlerClassTest.TestMothod1
[sf:deploy] Request Status: InProgress (29/268)  -- Running Test: caseCustProfile_Test.theTests
[sf:deploy] Request Status: InProgress (39/268)  -- Running Test: CaseWatchdogTest.testBuildEmailList
[sf:deploy] Request Status: InProgress (46/268)  -- Running Test: DisplayAssociatedAssetConfigurationTest.testMethod1
[sf:deploy] Request Status: InProgress (53/268)  -- Running Test: LicenseUIController.testInvokeMethodsForCoverage
[sf:deploy] Request Status: InProgress (53/268)  -- Running Test: LicenseUIController.testInvokeMethodsForCoverage
[sf:deploy] Request Status: InProgress (53/268)  -- Running Test: LicenseUIController.testInvokeMethodsForCoverage
[sf:deploy] Request Status: InProgress (60/268)  -- Running Test: LicenseUtilityController.testgenerateLicenseFileForReclaimWorkflow
[sf:deploy] Request Status: InProgress (70/268)  -- Running Test: NotificationController.testsendEmail
[sf:deploy] Request Status: InProgress (73/268)  -- Running Test: NtnxGenerateLicensesTest.testGenerateLicenses
[sf:deploy] Request Status: InProgress (77/268)  -- Running Test: NtnxPlatPlusRequestControllerTest.myUnitTest
[sf:deploy] Request Status: InProgress (80/268)  -- Running Test: NtnxUtilityExtension.testGetTAMPresent
[sf:deploy] Request Status: InProgress (98/268)  -- Running Test: OpportunityExtensionTest.testOpportunityExtension
[sf:deploy] Request Status: InProgress (100/268)  -- Running Test: OppSalesOrderRelatedListControllerTests.testInit
[sf:deploy] Request Status: InProgress (107/268)  -- Running Test: populateEmailNotificationFieldsTest.myUnitTest
[sf:deploy] Request Status: InProgress (116/268)  -- Running Test: SalesOrderUtilTest.testComma
[sf:deploy] Request Status: InProgress (120/268)  -- Running Test: SbqqQuoteUtilTest.myUnitTest
[sf:deploy] Request Status: InProgress (120/268)  -- Running Test: SbqqQuoteUtilTest.myUnitTest
[sf:deploy] Request Status: InProgress (120/268)  -- Running Test: SbqqQuoteUtilTest.myUnitTest
[sf:deploy] Request Status: InProgress (129/268)  -- Running Test: selfRegistrationController.getAccountNameTest
[sf:deploy] Request Status: InProgress (136/268)  -- Running Test: SurveyContestHandlerTest.testFoundWinnerNotificationEmail
[sf:deploy] Request Status: InProgress (147/268)  -- Running Test: TEST_CaseHandoffTimer.testPutCaseIntoQueue
[sf:deploy] Request Status: InProgress (150/268)  -- Running Test: testCeligoExplodeItemBundle.myUnitTest
[sf:deploy] Request Status: InProgress (156/268)  -- Running Test: testTriggers.testTrigger
[sf:deploy] Request Status: InProgress (168/268)  -- Running Test: Twilio_TestCalls.testTwilioCall_cancel
[sf:deploy] Request Status: InProgress (199/268)  -- Running Test: Twilio_TestNotification.testTwilioNotication_get
[sf:deploy] -----------------------------------------------------------------------------------
[sf:deploy] Test Failures:
[sf:deploy] 1.  Twilio_TestConference.testTwilioParticipants_get -- TwilioRestException: Script-thrown exception
[sf:deploy]     Stack trace: Class.TwilioRestClient: line 591, column 1
[sf:deploy]     Class.TwilioResource: line 82, column 1
[sf:deploy]     Class.TwilioResource.ListResource: line 463, column 1
[sf:deploy]     Class.TwilioParticipantList: line 87, column 1
[sf:deploy]     Class.Twilio_TestConference.testTwilioParticipants_get: line 212, column 1
[sf:deploy] -----------------------------------------------------------------------------------
[sf:deploy] Request Status: InProgress (229/268)  -- Running Test: Twilio_TestRestExceptn.test
[sf:deploy] Request Status: InProgress (256/268)  -- Running Test: updatePartnerCourseonAccountCtrlerTest.testinsertPartnerCourse
[sf:deploy] Request Status: InProgress (262/268)  -- Running Test: webservicesNetexamComUserservice71Test.DeactivateUserByExternalIDTest
[sf:deploy] Request Status: InProgress (266/268)  -- Running Test: webservicesNetexamComUserservice71Test.UpsertUserTest
[sf:deploy] Request Status: Failed

BUILD FAILED
/Users/samrudhipatil/codebase/twilio-salesforce-master/install/build.xml:9:
*********** DEPLOYMENT FAILED ***********
Request ID: 0Af60000000F5iaCAC

All Test Failures:
1.  Twilio_TestConference.testTwilioParticipants_get -- TwilioRestException: Script-thrown exception
    Stack trace: Class.TwilioRestClient: line 591, column 1
    Class.TwilioResource: line 82, column 1
    Class.TwilioResource.ListResource: line 463, column 1
    Class.TwilioParticipantList: line 87, column 1
    Class.Twilio_TestConference.testTwilioParticipants_get: line 212, column 1
*********** DEPLOYMENT FAILED ***********

Total time: 8 minutes 20 seconds

**Comment by Samrudhi** [comment]
The twilio deployment is failing on my production org, since the test above is failing.

**Comment by dschach** [comment]
Are you deploying straight from GitHub into Production? 
Please deploy into a Developer Edition org and run all tests to see if it still fails. Then deploy into Sandbox (preferably from the Developer org) and then into Production from Sandbox.
If you get errors at any of the earlier stages, it will help diagnose your problem.

**Comment by hhai** [comment]
In one of the last Merges we made a correction to the Conference URL, which wasn't updated in the test class.

Twilio_TestConference.cls LINE 204  You can correct the following mis-spelling 'Conferernces' to 'Conferences' which will match the Conference URL.

Twilio_TestHTTPMock.getInstance().putResponse(
			'GET',
			'https://api.twilio.com/2010-04-01/Accounts/AC03c2fcd60e144e7cbeee413fcbf812a3/Conferences/CFbbe46ff1274e283f7e3ac1df0072ab39/Participants.json',
			new Twilio_TestHTTPMock.Response(accountJsonResponseBody,200)

**Comment by Samrudhi** [comment]
Thanks hhai for the fix and quick response. I corrected the spelling in the test class and it fixed my issue. Hope we have merged the code for this fix so that other users do not face the same.

Thanks!
Samrudhi
