### ISSUE TITLE
Call redirect is throwing exception 404 even though uri is valid

### ISSUE THREAD

**Issue by kishorejena** [twilio/twilio-salesforce#53]
I have the following code running from developer console to redirect in progress calls to a conference room. Thought the URi of the call is valid the redirect is throwing  494 exception. Not sure why. Any help will be appreciated.

Here is my script.

TwilioRestClient client = TwilioAPI.getDefaultClient();
Map<String,String> filters = new Map<String,String>{'Status'=>'in-progress'};
Iterator<TwilioCall> calls = client.getAccount().getCalls(filters).iterator();
while (calls.hasNext()) {
    TwilioCall call = calls.next();
    System.Debug('Call Sid = '  + call.getSid());
    System.Debug('Call Parent Sid = '  + call.getParentCallSid());
    System.Debug('Call Uri = '  + call.getUri());

    if(call.getParentCallSid() != null)    
    call.redirect('http://test-businessfunding.cs10.force.com/conference',
            'POST'); 

}

Here is the error.

04:05:32:665 USER_DEBUG [8]|DEBUG|Call Uri = /2010-04-01/Accounts/AC5c27dcb4dd999d2aafc04c5d809d1483/Calls/CAde72b0c3dedadb4b9bc2f92405dbc1b6.json

04:05:32:720 USER_DEBUG [93]|DEBUG|RETURN: {code=20404, message=The requested resource /2010-04-01/Accounts/null/Calls/CAde72b0c3dedadb4b9bc2f92405dbc1b6.json was not found, more_info=https://www.twilio.com/docs/errors/20404, status=404}

One thing I noticed is that the resource has a null after account instead of the account SID. The uri for the call has real account SID. Not sure why.

Thanks

**Comment by kishorejena** [comment]
Sorry Typo there - it throws a 404 exception - resource not found

**Comment by hhai** [comment]
Make sure you have this code in the TwilioCallList.cls

That's where the accountSID will be set for each instance of the callList.

/* implements method from TwilioResource.ListResource */
public override Object makeNew(TwilioClient client,
Map<String, Object> params) {
TwilioCall call = new TwilioCall((TwilioRestClient)client, params);
call.setRequestAccountSid(this.getRequestAccountSid());
return call;
}


If you have an older version of the library it had a defect.

Henry Hai
*twilio* cloud communications
Solutions Architect
e: hhai@twilio.com
m: (646) 679-2731

https://join.me/henry_hai

**Comment by kishorejena** [comment]
?Thanks a lot Henry! Appreciate that.


I will try this and let you know if it solves.


- Kishore

________________________________

**Comment by kishorejena** [comment]
Hi Henry/Dan,


The issue is resolved now. Hopefully we can make some progress on the hot call transfer from the soft phone. Appreciate that.


Thanks,

Kishore



________________________________
